// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEGManagement.Infrastructure.Persistance;

#nullable disable

namespace WEGManagement.Infrastructure.Migrations
{
    [DbContext(typeof(WegDbContext))]
    [Migration("20260923121419_InitWegManagement")]
    partial class InitWegManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEGManagement.Domain.Models.Apartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfResidents")
                        .HasColumnType("int");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Size")
                        .HasColumnType("real");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Address = "742 Evergreen Terrace, Wohnung 1",
                            BuildingId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Floor = 1,
                            NumberOfResidents = 2,
                            OwnerId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Size = 82.5f,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Address = "742 Evergreen Terrace, Wohnung 2",
                            BuildingId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Floor = 2,
                            NumberOfResidents = 1,
                            OwnerId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Size = 96f,
                            Status = 1
                        });
                });

            modelBuilder.Entity("WEGManagement.Domain.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Address = "742 Evergreen Terrace, Springfield"
                        });
                });

            modelBuilder.Entity("WEGManagement.Domain.Models.CondoFee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("CondoFees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Amount = 285.00m,
                            ApartmentId = new Guid("20000000-0000-0000-0000-000000000001"),
                            DueDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Amount = 285.00m,
                            ApartmentId = new Guid("20000000-0000-0000-0000-000000000001"),
                            DueDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = 2
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Amount = 340.00m,
                            ApartmentId = new Guid("20000000-0000-0000-0000-000000000002"),
                            DueDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = 0
                        });
                });

            modelBuilder.Entity("WEGManagement.Domain.Models.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankConnection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            BankConnection = "DEMO-BANK-0001",
                            Contact = "bugs.bunny@example.test",
                            Name = "Bugs Bunny"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            BankConnection = "DEMO-BANK-0002",
                            Contact = "leela@example.test",
                            Name = "Turanga Leela"
                        });
                });

            modelBuilder.Entity("WEGManagement.Domain.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CondoFeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CondoFeeId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Amount = 285.00m,
                            CondoFeeId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Date = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentType = 0,
                            Reference = "40000000-0000-0000-0000-000000000001"
                        });
                });

            modelBuilder.Entity("WEGManagement.Domain.Models.RepairOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Craftsman")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("RepairOrders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            BuildingId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Cost = 1250.00m,
                            Craftsman = "Acme Roofing",
                            Date = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dachrinne am Nordflügel prüfen und reparieren",
                            Priority = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            BuildingId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Cost = 680.00m,
                            Craftsman = "Planet Express Maintenance",
                            Date = new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aufzug: Türsensor austauschen",
                            Priority = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            BuildingId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Cost = 420.00m,
                            Craftsman = "MomCorp Services",
                            Date = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Heizungsanlage warten",
                            Priority = 0,
                            Status = 2
                        });
                });

            modelBuilder.Entity("WEGManagement.Domain.Models.Apartment", b =>
                {
                    b.HasOne("WEGManagement.Domain.Models.Building", "Building")
                        .WithMany("Apartments")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEGManagement.Domain.Models.Owner", "Owner")
                        .WithMany("Apartments")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WEGManagement.Domain.Models.CondoFee", b =>
                {
                    b.HasOne("WEGManagement.Domain.Models.Apartment", "Apartment")
                        .WithMany("CondoFees")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("WEGManagement.Domain.Models.Payment", b =>
                {
                    b.HasOne("WEGManagement.Domain.Models.CondoFee", "CondoFee")
                        .WithMany("Payments")
                        .HasForeignKey("CondoFeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CondoFee");
                });

            modelBuilder.Entity("WEGManagement.Domain.Models.RepairOrder", b =>
                {
                    b.HasOne("WEGManagement.Domain.Models.Building", "Building")
                        .WithMany("RepairOrders")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("WEGManagement.Domain.Models.Apartment", b =>
                {
                    b.Navigation("CondoFees");
                });

            modelBuilder.Entity("WEGManagement.Domain.Models.Building", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("RepairOrders");
                });

            modelBuilder.Entity("WEGManagement.Domain.Models.CondoFee", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WEGManagement.Domain.Models.Owner", b =>
                {
                    b.Navigation("Apartments");
                });
#pragma warning restore 612, 618
        }
    }
}
